import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { useHomeLocationFeed } from "../hooks/useLocations";
export const PlacesFeedSection = ({ userId, title = "From places you follow", maxItems = 10 }) => {
    const [expanded, setExpanded] = useState(false);
    const { feedItems, loading, hasMore, loadMore } = useHomeLocationFeed(userId, maxItems);
    if (loading && feedItems.length === 0) {
        return (_jsx("div", { className: "bg-white rounded-lg shadow-sm border border-gray-200 p-6", children: _jsx("div", { className: "flex items-center justify-center py-8", children: _jsx("div", { className: "animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600" }) }) }));
    }
    if (feedItems.length === 0) {
        return (_jsx("div", { className: "bg-white rounded-lg shadow-sm border border-gray-200 p-6", children: _jsxs("div", { className: "text-center py-8", children: [_jsx("div", { className: "text-gray-400 text-6xl mb-4", children: "\uD83C\uDFDF\uFE0F" }), _jsx("h3", { className: "text-lg font-medium text-gray-900 mb-2", children: "No places followed yet" }), _jsx("p", { className: "text-gray-500", children: "Follow some places to see their updates here!" })] }) }));
    }
    const displayedItems = expanded ? feedItems : feedItems.slice(0, maxItems);
    const hasHiddenItems = feedItems.length > maxItems;
    return (_jsxs("div", { className: "bg-white rounded-lg shadow-sm border border-gray-200", children: [_jsx("div", { className: "px-6 py-4 border-b border-gray-200", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-lg font-semibold text-gray-900", children: title }), _jsxs("p", { className: "text-sm text-gray-500", children: [feedItems.length, " update", feedItems.length !== 1 ? "s" : "", " from your followed places"] })] }), hasHiddenItems && (_jsx("button", { onClick: () => setExpanded(!expanded), className: "text-sm text-blue-600 hover:text-blue-800 font-medium", children: expanded ? "Show Less" : `Show ${feedItems.length - maxItems} More` }))] }) }), _jsx("div", { className: "divide-y divide-gray-200", children: displayedItems.map((feedItem) => (_jsxs("div", { className: "p-6", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("span", { className: "text-sm text-gray-500", children: "\uD83C\uDFDF\uFE0F" }), _jsx("span", { className: "text-sm font-medium text-gray-900", children: feedItem.source.kind === "location" ? "Location Update" : "Update" }), _jsxs("span", { className: "text-xs text-gray-400", children: ["Rank: ", feedItem.rank.toFixed(1)] })] }), _jsx("span", { className: "text-xs text-gray-400", children: new Date(feedItem.createdAt).toLocaleDateString() })] }), _jsxs("div", { className: "bg-gray-50 rounded-md p-4", children: [_jsx("p", { className: "text-sm text-gray-600", children: _jsxs("em", { children: ["Post content would be loaded here based on ", feedItem.postRef] }) }), _jsxs("p", { className: "text-xs text-gray-400 mt-2", children: ["Reference: ", feedItem.postRef] })] })] }, feedItem.id))) }), hasMore && (_jsx("div", { className: "px-6 py-4 border-t border-gray-200", children: _jsx("button", { onClick: loadMore, className: "w-full bg-gray-50 text-gray-700 px-4 py-2 rounded-md text-sm font-medium hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500", children: "Load More Updates" }) })), hasHiddenItems && (_jsx("div", { className: "px-6 py-3 border-t border-gray-200 bg-gray-50", children: _jsx("button", { onClick: () => setExpanded(!expanded), className: "w-full text-center text-sm text-blue-600 hover:text-blue-800 font-medium", children: expanded ? "Show Less" : `Show ${feedItems.length - maxItems} More Updates` }) }))] }));
};
