sport: basketball
skills:
  - name: shooting
    metrics:
      - accuracy
      - range
  - name: dribbling
    metrics:
      - speed
      - control
  - name: conditioning
    metrics:
      - endurance
      - agility
logic:
  plateau: "repeat drill with variation"
  improvement: "advance to next level drill"
  decline: "focus on fundamentals" 