global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # SportBeaconAI Backend
  - job_name: 'sportbeacon-backend'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'

  # SportBeaconAI Frontend
  - job_name: 'sportbeacon-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter (System metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker:9323']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Custom application metrics
  - job_name: 'sportbeacon-custom'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/api/metrics'
    scrape_interval: 60s
    scrape_timeout: 15s
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        regex: '([^:]+)'
        replacement: 'sportbeacon-backend'

  # Health checks
  - job_name: 'health-checks'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/health'
    scrape_interval: 60s
    scrape_timeout: 10s
    honor_labels: true
    metrics_path: '/health'
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        regex: '([^:]+)'
        replacement: 'sportbeacon-backend' 