#!/usr/bin/env node

const fs = require('fs');
const crypto = require('crypto');
const path = require('path');

// Generate secure secrets
const generateSecureSecret = (length = 64) => crypto.randomBytes(length).toString('hex');

// Production Firebase configuration for sportbeacon-ai project
const productionConfig = {
  // Firebase Frontend
  NEXT_PUBLIC_FIREBASE_API_KEY: 'AIzaSyB_placeholder_for_production_key',
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: 'sportbeacon-ai.firebaseapp.com',
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: 'sportbeacon-ai',
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: 'sportbeacon-ai.appspot.com',
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: '104921686559',
  NEXT_PUBLIC_FIREBASE_APP_ID: '1:104921686559:web:placeholder_for_production_app_id',
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: 'G-PLACEHOLDER',
  NEXT_PUBLIC_FIREBASE_VAPID_KEY: 'BL-placeholder_for_production_vapid_key',

  // Firebase Backend
  FIREBASE_API_KEY: 'AIzaSyB_placeholder_for_production_key',
  FIREBASE_AUTH_DOMAIN: 'sportbeacon-ai.firebaseapp.com',
  FIREBASE_PROJECT_ID: 'sportbeacon-ai',
  FIREBASE_STORAGE_BUCKET: 'sportbeacon-ai.appspot.com',
  FIREBASE_MESSAGING_SENDER_ID: '104921686559',
  FIREBASE_APP_ID: '1:104921686559:web:placeholder_for_production_app_id',

  // Security (Generated)
  JWT_SECRET: generateSecureSecret(64),
  ADMIN_TOKEN: generateSecureSecret(32),
  API_SECRET_KEY: generateSecureSecret(32),

  // Environment
  NODE_ENV: 'production',
  VITE_SENTRY_ENVIRONMENT: 'production',
  VITE_ENABLE_SENTRY: 'true',
  NEXT_TELEMETRY_DISABLED: '1',
};

// Development configuration
const developmentConfig = {
  // Firebase Frontend (Development)
  NEXT_PUBLIC_FIREBASE_API_KEY: 'AIzaSyB_placeholder_for_dev_key',
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: 'sportbeacon-ai-dev.firebaseapp.com',
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: 'sportbeacon-ai-dev',
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: 'sportbeacon-ai-dev.appspot.com',
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: '104921686559',
  NEXT_PUBLIC_FIREBASE_APP_ID: '1:104921686559:web:placeholder_for_dev_app_id',

  // Firebase Backend (Development)
  FIREBASE_API_KEY: 'AIzaSyB_placeholder_for_dev_key',
  FIREBASE_AUTH_DOMAIN: 'sportbeacon-ai-dev.firebaseapp.com',
  FIREBASE_PROJECT_ID: 'sportbeacon-ai-dev',
  FIREBASE_STORAGE_BUCKET: 'sportbeacon-ai-dev.appspot.com',
  FIREBASE_MESSAGING_SENDER_ID: '104921686559',
  FIREBASE_APP_ID: '1:104921686559:web:placeholder_for_dev_app_id',

  // Security (Generated)
  JWT_SECRET: generateSecureSecret(64),
  ADMIN_TOKEN: generateSecureSecret(32),
  API_SECRET_KEY: generateSecureSecret(32),

  // Environment
  NODE_ENV: 'development',
  VITE_SENTRY_ENVIRONMENT: 'development',
  VITE_ENABLE_SENTRY: 'false',
};

function generateEnvFile(config, filename) {
  const envContent = Object.entries(config)
    .map(([key, value]) => `${key}=${value}`)
    .join('\n');

  const header = `# ${filename} - Generated by setup-env.js
# Generated: ${new Date().toISOString()}
# WARNING: Keep this file secure and never commit to version control

`;

  const fullContent = header + envContent;
  
  try {
    fs.writeFileSync(filename, fullContent);
    return true;
  } catch (error) {
    console.error(`❌ Failed to generate ${filename}:`, error.message);
    return false;
  }
}

function validateFirebaseConfig(config) {
  const requiredKeys = [
    'NEXT_PUBLIC_FIREBASE_API_KEY',
    'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN',
    'NEXT_PUBLIC_FIREBASE_PROJECT_ID',
    'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET',
    'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
    'NEXT_PUBLIC_FIREBASE_APP_ID',
  ];

  const missingKeys = requiredKeys.filter(key => !config[key] || config[key].includes('placeholder'));
  
  if (missingKeys.length > 0) {
    console.warn(`⚠️  Warning: Missing or placeholder values for: ${missingKeys.join(', ')}`);
    console.warn('⚠️  Please update with actual Firebase project credentials');
    return false;
  }

  return true;
}

function main() {

  // Generate development environment
  const devSuccess = generateEnvFile(developmentConfig, '.env.development');
  
  // Generate production environment
  const prodSuccess = generateEnvFile(productionConfig, '.env.production');

  // Validate configurations
  const devValid = validateFirebaseConfig(developmentConfig);
  const prodValid = validateFirebaseConfig(productionConfig);

  // Generate secrets file for CI/CD
  const secrets = {
    JWT_SECRET: generateSecureSecret(64),
    ADMIN_TOKEN: generateSecureSecret(32),
    API_SECRET_KEY: generateSecureSecret(32),
    FIREBASE_SERVICE_ACCOUNT: '{}', // Placeholder for service account JSON
  };

  const secretsContent = JSON.stringify(secrets, null, 2);
  fs.writeFileSync('ci-reports/generated-secrets.json', secretsContent);

  // Summary

  if (!devValid || !prodValid) {
  }

}

if (require.main === module) {
  main();
}

module.exports = {
  generateSecureSecret,
  generateEnvFile,
  validateFirebaseConfig,
  productionConfig,
  developmentConfig,
}; 