export declare const UserRoleSchema: any;
export declare const UserPreferencesSchema: any;
export declare const UserSchema: any;
export declare const CreateUserSchema: any;
export declare const UpdateUserSchema: any;
export declare const AuthContextSchema: any;
export declare const PlayerPositionSchema: any;
export declare const SkillLevelSchema: any;
export declare const PlayerStatsSchema: any;
export declare const EmergencyContactSchema: any;
export declare const MedicalInfoSchema: any;
export declare const PlayerSchema: any;
export declare const CreatePlayerSchema: any;
export declare const UpdatePlayerSchema: any;
export declare const TeamColorsSchema: any;
export declare const TeamStatsSchema: any;
export declare const TeamSchema: any;
export declare const CreateTeamSchema: any;
export declare const UpdateTeamSchema: any;
export declare const LeagueStatusSchema: any;
export declare const LeagueRulesSchema: any;
export declare const AgeGroupSchema: any;
export declare const DivisionSchema: any;
export declare const LeagueSchema: any;
export declare const CreateLeagueSchema: any;
export declare const UpdateLeagueSchema: any;
export declare const GameStatusSchema: any;
export declare const GameScoreSchema: any;
export declare const GameEventTypeSchema: any;
export declare const GameEventSchema: any;
export declare const GameSchema: any;
export declare const CreateGameSchema: any;
export declare const UpdateGameSchema: any;
export declare const AddressSchema: any;
export declare const ContactInfoSchema: any;
export declare const FacilityTypeSchema: any;
export declare const SurfaceTypeSchema: any;
export declare const FacilitySchema: any;
export declare const VenueAvailabilitySchema: any;
export declare const VenuePricingSchema: any;
export declare const VenueSchema: any;
export declare const CreateVenueSchema: any;
export declare const UpdateVenueSchema: any;
export declare const PaymentStatusSchema: any;
export declare const PaymentTypeSchema: any;
export declare const PaymentMethodSchema: any;
export declare const PaymentSchema: any;
export declare const CreatePaymentSchema: any;
export declare const UpdatePaymentSchema: any;
export declare const NotificationTypeSchema: any;
export declare const NotificationPrioritySchema: any;
export declare const NotificationSchema: any;
export declare const CreateNotificationSchema: any;
export declare const UpdateNotificationSchema: any;
export declare const ApiResponseSchema: <T extends z.ZodTypeAny>(dataSchema: T) => any;
export declare const PaginatedResponseSchema: <T extends z.ZodTypeAny>(dataSchema: T) => any;
export declare const ValidationRuleSchema: any;
export declare const ValidationSchema: any;
export declare const Schemas: {
    readonly User: any;
    readonly CreateUser: any;
    readonly UpdateUser: any;
    readonly UserRole: any;
    readonly UserPreferences: any;
    readonly AuthContext: any;
    readonly Player: any;
    readonly CreatePlayer: any;
    readonly UpdatePlayer: any;
    readonly PlayerPosition: any;
    readonly SkillLevel: any;
    readonly PlayerStats: any;
    readonly EmergencyContact: any;
    readonly MedicalInfo: any;
    readonly Team: any;
    readonly CreateTeam: any;
    readonly UpdateTeam: any;
    readonly TeamColors: any;
    readonly TeamStats: any;
    readonly League: any;
    readonly CreateLeague: any;
    readonly UpdateLeague: any;
    readonly LeagueStatus: any;
    readonly LeagueRules: any;
    readonly AgeGroup: any;
    readonly Division: any;
    readonly Game: any;
    readonly CreateGame: any;
    readonly UpdateGame: any;
    readonly GameStatus: any;
    readonly GameScore: any;
    readonly GameEvent: any;
    readonly GameEventType: any;
    readonly Venue: any;
    readonly CreateVenue: any;
    readonly UpdateVenue: any;
    readonly Address: any;
    readonly ContactInfo: any;
    readonly Facility: any;
    readonly FacilityType: any;
    readonly SurfaceType: any;
    readonly VenueAvailability: any;
    readonly VenuePricing: any;
    readonly Payment: any;
    readonly CreatePayment: any;
    readonly UpdatePayment: any;
    readonly PaymentStatus: any;
    readonly PaymentType: any;
    readonly PaymentMethod: any;
    readonly Notification: any;
    readonly CreateNotification: any;
    readonly UpdateNotification: any;
    readonly NotificationType: any;
    readonly NotificationPriority: any;
    readonly ApiResponse: <T extends z.ZodTypeAny>(dataSchema: T) => any;
    readonly PaginatedResponse: <T_1 extends z.ZodTypeAny>(dataSchema: T_1) => any;
    readonly ValidationRule: any;
    readonly ValidationSchema: any;
};
export type SchemasType = typeof Schemas;
//# sourceMappingURL=user.d.ts.map